services:
  log_collector:
    build: ./fluentd
    container_name: fluetd
    ports:
      - "9880:9880"
    
  the_zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: the_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker_one:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker_one
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - the_zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'the_zookeeper:2181' 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_one:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  goapp:
    build: ./golang
    container_name: goapp
    depends_on:
      - broker_one
    volumes:
      - type: bind
        source: ./golang
        target: /usr/src/app
